workflows:
  default:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set working directory and get dependencies
        script: |
          cd blank_app
          flutter pub get
          cd ios
          pod install
      - name: Build iOS
        script: |
          cd blank_app
          flutter build ios --release --no-codesign
    artifacts:
      - blank_app/build/ios/iphoneos/*.app
