workflows:
  default:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FCI_FLUTTER_SCHEME: Runner
    scripts:
      - name: Get Flutter dependencies
        script: |
          cd $CM_BUILD_DIR/blank_app
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd $CM_BUILD_DIR/blank_app/ios
          pod install
      - name: Build iOS app
        script: |
          cd $CM_BUILD_DIR/blank_app
          flutter build ios --debug --no-codesign
    artifacts:
      - blank_app/build/ios/iphoneos/*.app
