workflows:
  # ========================================
  # ðŸŒ WEB PREVIEW WORKFLOW
  # Production-grade web build for deployment
  # ========================================
  web-preview:
    name: Flutter Web - Production Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    working_directory: flutter_app
    environment:
      flutter: stable
      xcode: latest
      vars:
        FLUTTER_BUILD_MODE: release
        WEB_RENDERER: canvaskit
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - .dart_tool
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'develop'
          include: true
        - pattern: 'feature/*'
          include: true
    scripts:
      - name: ðŸ” Get Flutter packages
        script: |
          flutter pub get
          
      - name: ðŸ§¹ Clean previous builds
        script: |
          flutter clean
          flutter pub get
          
      - name: ðŸ”§ Generate code (if needed)
        script: |
          # Uncomment if using code generation
          # flutter pub run build_runner build --delete-conflicting-outputs
          echo "Skipping code generation"
          
      - name: âœ… Run code analysis
        script: |
          flutter analyze
          
      - name: ðŸ§ª Run unit tests
        script: |
          flutter test
        
      - name: ðŸ—ï¸ Build Flutter Web (Production)
        script: |
          set -e
          echo "ðŸ—ï¸  Starting Fidora Flutter Web build..."
          
          # Check if --web-renderer flag is supported
          if flutter build web -h | grep -q -- "--web-renderer"; then
            echo "âœ… Using supported --web-renderer flag (${WEB_RENDERER:-canvaskit})"
            flutter build web \
              --release \
              --web-renderer "${WEB_RENDERER:-canvaskit}" \
              --dart-define=ENVIRONMENT=production \
              --dart-define=FIDORA_ENV=production
          else
            echo "âš ï¸  --web-renderer not supported in this Flutter version. Proceeding without it..."
            flutter build web \
              --release \
              --dart-define=ENVIRONMENT=production \
              --dart-define=FIDORA_ENV=production
          fi
          
          echo "âœ… Build completed successfully!"
            
      - name: ðŸ“Š Bundle size analysis
        script: |
          echo "ðŸ“¦ Web build output size:"
          du -sh build/web
          echo ""
          echo "ðŸ“„ Main bundle size:"
          du -h build/web/main.dart.js 2>/dev/null || echo "main.dart.js not found"
          
      - name: ðŸŽ¯ Optimize assets
        script: |
          echo "âœ¨ Web build ready for deployment"
          ls -lah build/web
    artifacts:
      - build/web/**
    publishing:
      email:
        recipients:
          - engineering@example.com
        notify:
          success: true
          failure: true

  # ========================================
  # ðŸ“± iOS PRODUCTION WORKFLOW
  # Enterprise iOS build with App Store deployment
  # ========================================
  ios-production:
    name: iOS - Production Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    working_directory: flutter_app
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.enterprise.flutter_app
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_STORE_APPLE_ID: 1234567890
        BUNDLE_ID: com.enterprise.flutter_app
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Caches/CocoaPods
        - ios/Pods
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*.*.*'
          include: true
    scripts:
      - name: ðŸ” Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles
          
      - name: ðŸ“¦ Get Flutter packages
        script: |
          flutter pub get
          
      - name: ðŸŽ Install CocoaPods
        script: |
          cd ios
          pod install
          
      - name: ðŸ—ï¸ Build iOS App
        script: |
          flutter build ipa \
            --release \
            --export-options-plist=/Users/builder/export_options.plist \
            --dart-define=ENVIRONMENT=production
            
      - name: ðŸ“Š App size analysis
        script: |
          echo "ðŸ“¦ IPA size:"
          du -sh build/ios/ipa/*.ipa
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/Runner.xcarchive/**/*
    publishing:
      email:
        recipients:
          - ios-team@example.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
        submit_to_app_store: false

  # ========================================
  # ðŸ¤– ANDROID PRODUCTION WORKFLOW
  # Enterprise Android build with Play Store deployment
  # ========================================
  android-production:
    name: Android - Production Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    working_directory: flutter_app
    environment:
      android_signing:
        - enterprise_keystore
      flutter: stable
      xcode: latest
      vars:
        PACKAGE_NAME: com.enterprise.flutter_app
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/.gradle/caches
        - .dart_tool
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*.*.*'
          include: true
    scripts:
      - name: ðŸ” Set up keystore
        script: |
          echo $ANDROID_KEYSTORE_FILE | base64 --decode > $CM_BUILD_DIR/keystore.jks
          cat >> "$CM_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$ANDROID_KEYSTORE_PASSWORD
          keyPassword=$ANDROID_KEY_PASSWORD
          keyAlias=$ANDROID_KEY_ALIAS
          storeFile=$CM_BUILD_DIR/keystore.jks
          EOF
          
      - name: ðŸ“¦ Get Flutter packages
        script: |
          flutter pub get
          
      - name: ðŸ—ï¸ Build Android App Bundle
        script: |
          flutter build appbundle \
            --release \
            --dart-define=ENVIRONMENT=production
            
      - name: ðŸ—ï¸ Build Android APK
        script: |
          flutter build apk \
            --release \
            --split-per-abi \
            --dart-define=ENVIRONMENT=production
            
      - name: ðŸ“Š App size analysis
        script: |
          echo "ðŸ“¦ AAB size:"
          du -sh build/app/outputs/bundle/release/*.aab
          echo ""
          echo "ðŸ“¦ APK sizes:"
          du -sh build/app/outputs/flutter-apk/*.apk
    artifacts:
      - build/app/outputs/bundle/release/*.aab
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/mapping/release/mapping.txt
    publishing:
      email:
        recipients:
          - android-team@example.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true

  # ========================================
  # ðŸ”„ STAGING WORKFLOW
  # Automated staging builds for QA testing
  # ========================================
  web-staging:
    name: Flutter Web - Staging Build
    instance_type: mac_mini_m2
    max_build_duration: 45
    working_directory: flutter_app
    environment:
      flutter: stable
      xcode: latest
      vars:
        FLUTTER_BUILD_MODE: release
        WEB_RENDERER: canvaskit
    cache:
      cache_paths:
        - $HOME/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'develop'
          include: true
        - pattern: 'staging'
          include: true
    scripts:
      - name: ðŸ“¦ Get dependencies
        script: |
          flutter pub get
          
      - name: ðŸ—ï¸ Build for staging
        script: |
          set -e
          echo "ðŸ—ï¸  Starting Fidora Flutter Web build (Staging)..."
          
          # Check if --web-renderer flag is supported
          if flutter build web -h | grep -q -- "--web-renderer"; then
            echo "âœ… Using supported --web-renderer flag (${WEB_RENDERER:-canvaskit})"
            flutter build web \
              --release \
              --web-renderer "${WEB_RENDERER:-canvaskit}" \
              --dart-define=ENVIRONMENT=staging \
              --dart-define=FIDORA_ENV=staging
          else
            echo "âš ï¸  --web-renderer not supported in this Flutter version. Proceeding without it..."
            flutter build web \
              --release \
              --dart-define=ENVIRONMENT=staging \
              --dart-define=FIDORA_ENV=staging
          fi
          
          echo "âœ… Staging build completed successfully!"
    artifacts:
      - build/web/**
    publishing:
      email:
        recipients:
          - qa-team@example.com
        notify:
          success: true
          failure: true

  # ========================================
  # ðŸ§ª DEVELOPMENT/PR WORKFLOW
  # Quick validation for pull requests
  # ========================================
  pr-check:
    name: PR Quality Checks
    instance_type: mac_mini_m2
    max_build_duration: 30
    working_directory: flutter_app
    environment:
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - $HOME/.pub-cache
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
    scripts:
      - name: ðŸ“¦ Get dependencies
        script: |
          flutter pub get
          
      - name: ðŸ” Format check
        script: |
          flutter format --set-exit-if-changed .
          
      - name: âœ… Analyze code
        script: |
          flutter analyze
          
      - name: ðŸ§ª Run tests
        script: |
          flutter test
          
      - name: ðŸ—ï¸ Build test (Android)
        script: |
          flutter build apk --debug
    publishing:
      email:
        recipients:
          - dev-team@example.com
        notify:
          success: false
          failure: true
