workflows:
  default:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    working_directory: blank_app
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build iOS app
        script: flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
