workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        # Set project path since Flutter app is in subdirectory
        FLUTTER_PROJECT_PATH: "blank_app"
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $FLUTTER_PROJECT_PATH/.dart_tool
        - $FLUTTER_PROJECT_PATH/ios/Pods
    scripts:
      - name: Get Flutter packages
        script: |
          cd $FLUTTER_PROJECT_PATH
          flutter packages pub get
      - name: Install iOS dependencies
        script: |
          cd $FLUTTER_PROJECT_PATH/ios
          pod install
      - name: Flutter analyze
        script: |
          cd $FLUTTER_PROJECT_PATH
          flutter analyze
      - name: Build iOS (no signing)
        script: |
          cd $FLUTTER_PROJECT_PATH
          flutter build ios --no-codesign --release
    artifacts:
      - $FLUTTER_PROJECT_PATH/build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true

  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      flutter: stable
      java: 17
      vars:
        FLUTTER_PROJECT_PATH: "blank_app"
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $FLUTTER_PROJECT_PATH/.dart_tool
        - $HOME/.gradle/caches
    scripts:
      - name: Get Flutter packages
        script: |
          cd $FLUTTER_PROJECT_PATH
          flutter packages pub get
      - name: Flutter analyze
        script: |
          cd $FLUTTER_PROJECT_PATH
          flutter analyze
      - name: Build Android APK
        script: |
          cd $FLUTTER_PROJECT_PATH
          flutter build apk --release
      - name: Build Android App Bundle
        script: |
          cd $FLUTTER_PROJECT_PATH
          flutter build appbundle --release
    artifacts:
      - $FLUTTER_PROJECT_PATH/build/app/outputs/**/*.apk
      - $FLUTTER_PROJECT_PATH/build/app/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
