workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Navigate to Flutter project and get dependencies
        script: |
          cd blank_app
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd blank_app/ios
          pod install
      - name: Build iOS app
        script: |
          cd blank_app
          flutter build ios --release --no-codesign
    artifacts:
      - blank_app/build/ios/**/*.app

  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Navigate to Flutter project and get dependencies
        script: |
          cd blank_app
          flutter pub get
      - name: Build Android APK
        script: |
          cd blank_app
          flutter build apk --release
    artifacts:
      - blank_app/build/app/outputs/**/*.apk
